x=int(input("Bhaiyya pehla number de do"))
y=int(input("Bhaiya ab doosra bhi de do"))
print(x+y)
print(x/y)
print(x*y)
print("ijepgjjjjgpjpejjjjkmf;bnmjjjj;mefg;jjjjkng;ejjjj;kkfg;kefgjjjj;ejg;kjgf")
